### ISSUE TITLE
Volume Increase Or Decrease 

### ISSUE THREAD

**Issue by ashishsiot** [pseudosavant/player.html#10]
There Is a Volume Button  By That Button We Just Mute🔇 Or Unmute🔊 Volume Can We Add Volume Increase🔈🔉🔊 Or Decrease🔊🔉🔈 Slider Button To It 
I Think It Is Very Common Function That Users Can Use Or Users What That Button Present On Website 
-Thank You🙏

**Comment by pseudosavant** [comment]
I added it into my backlog to investigate. Personally, I have mixed feelings on per video volume adjustment beyond mute as users can get into a funny 'nesting' of volumes: system level, app level, per video level, but I'll look into how I could expose that in the UI.

**Comment by pseudosavant** [comment]
@ashishsiot check out the latest v2.1 release. I added in some basic volume control. https://github.com/pseudosavant/player.html/releases/tag/2.1.0
