### ISSUE TITLE
Unable to load mkv file format

### ISSUE THREAD

**Issue by syisahi12** [pseudosavant/player.html#11]
I using uhttpd, all feture is fine except mkv file. please help me
thank you

**Comment by pseudosavant** [comment]
Can you share more detail on the problems you are experiencing? Does it not show the `mkv` files in the file list or does it just not play correctly? Can you share a screenshot of the browser dev tools console after loading `player.html` and after experiencing the issue?

File support in `player.html` in completely dependent on what formats your browser's video engine supports. `player.html` does a check on startup to see what video mime types your browser supports and prints the results to the console. That information is then used to determine what file extensions to show (or not).

![image](https://user-images.githubusercontent.com/455424/108113859-e4992800-704c-11eb-9c24-fa9a3d1286a3.png)

Generally, MKV support in browsers is poor, except for WebM. WebM is actually an MKV file with VP8/9 video and Vorbis/Opus audio tracks. But most `.mkv` files you will find in the wild will be using H264/H265 for video and AC3/AAC/MP3, and most browsers will not support that.

This little script will tell you what mime types your browser supports:

```js
var v = document.createElement('video');
['video/mp4', 'video/webm', 'video/x-matroska','video/ogg'].forEach(
  (m) => console.log(`${m}: ${v.canPlayType(m) !== ''}`)
);
```
