### ISSUE TITLE
Request: Server-side thumbnails

### ISSUE THREAD

**Issue by giddyhup** [pseudosavant/player.html#16]
The solution is exactly what I was looking for for browsing through daily time lapse videos. Thank you!

Would it be possible to add an option to support and give preference to server-side thumbnails rather than generating and storing them on the client? I'd rather generate the thumbnails programmatically at night on the server than to rely on the storage and compute power of the client. 

Would it be possible to exclude directories from the navigation (e.g. '/' or '/css')?

**Comment by pseudosavant** [comment]
I've considered server-side rendering in the past, but it is against the ethos of this project of being a 1 file video player that works with any basic HTTP directory serving. It should not require any setup on the server side.

One option that may work would be supporting showing thumbnail files that are adjacent to the video files (e.g. `myVideo.mp4` and `myVideo.jpg` or `myVideo.thumbnail.png`). That way you can create a server-side thumbnail rendering without requiring anything beyond basic HTTP serving.

On the directory exclusion, I'm fine with the concept, but I don't want to filter by default. There would need to be a way to configure what folders should be excluded: in file config, in the UI, etc. That is the more complicated matter. It should be opened as its own request though.

**Comment by giddyhup** [comment]
Thank you for replying. I totally understand and like the simplistic approach. I don't expect your solution to actually generate the thumbnails so supporting neighboring files (following any naming convention you want to support) would totally work.

I'll open a new issue about filtering directories.

**Comment by blautob** [comment]
I would love the thumbnail feature you described above.

**Comment by pseudosavant** [comment]
Hey @blautob and @giddyhup! Glad you like this project. I'm working on a potential way to retrieve server-side thumbnails and fallback on ones generated in the browser.

Is there a filename structure that you use or is common (e.g. myVideo.thumb.jpg)?

**Comment by blautob** [comment]
I would currently go with the same filename.png as the videofile

**Comment by giddyhup** [comment]
@pseudosavant, Thanks for considering this. I have no preference. I would keep the string to be put in the filename as short as posssible to not make file names too long. So perhaps ORIGINALNAME_tn.EXT or 'th' or 'tl'.

**Comment by blautob** [comment]
for me a sample file looks like:
62229dc12c9e43b89d8b78ad1a3b9634.mp4
62229dc12c9e43b89d8b78ad1a3b9634.jpg

**Comment by giddyhup** [comment]
My files have follow a YYYYMMDDhhmmss.mp4 or YYYYMMDD.mp4 format, so YYYYMMDDhhmmss_tn.jpg would work for me. Yet, since I would generate the thumbnails myself I could generate any expected format.

**Comment by pseudosavant** [comment]
Based on feedback and from looking around online, it seems like the most common pattern is to just replace the video filename extension (`myVideo.mp4`) with `jpg` (`myVideo.jpg`). I will be following that structure.

This implementation is not limited to just `jpg` files though. It was easy to support all of the common browser image format extensions (gif, jpeg, jpg, webp, png). Choose whichever you prefer.

**Comment by pseudosavant** [comment]
Give v2.2.7 a try: https://github.com/pseudosavant/player.html/releases/tag/2.2.7

**Comment by blautob** [comment]
works like a charm!

**Comment by giddyhup** [comment]
Thanks for implementing this. The thumbnails seem to be picked up and are shown but they disappear after the playback symbol animation when hovering over it.

**Comment by pseudosavant** [comment]
Indeed, they do disappear. That is what I get for deving on a machine using mostly the touchscreen instead of the mouse. I didn't do any hovering really I guess. Should be easy to address.

**Comment by pseudosavant** [comment]
@giddyhup Check out 2.2.8: https://github.com/pseudosavant/player.html/releases/tag/2.2.8

**Comment by giddyhup** [comment]
It works perfectly now, thank you for implementing this.
