### ISSUE TITLE
A minor issue on play/pause button

### ISSUE THREAD

**Issue by VisImage** [pseudosavant/player.html#18]
Thanks for the sharing. I like the idea that all in one file.  Just noticed an issue.  In the general convention, a triangle shaped button is displayed when the video is paused. But this player is opposite.  Texted on Chrome and MS Edge.

**Comment by pseudosavant** [comment]
You are right, it is backwards of the typical convention. I switched it. The fix will be in the next release.

**Comment by pseudosavant** [comment]
@VisImage Check out v2.2.9 it should fix this.
