### ISSUE TITLE
Autoindex folder's name from apache / error

### ISSUE THREAD

**Issue by tomtoom1978** [pseudosavant/player.html#25]
I cannot fix the problem with 4 folders from apache indexation.

![Capture d’écran du 2023-10-29 12-18-56](https://github.com/pseudosavant/player.html/assets/36678395/76bbbb46-617f-4002-ac18-d47ffa58ab2c)
thanks

**Comment by pseudosavant** [comment]
Hi @tomtoom1978,

Could you share what that same folder looks like when rendered by Apache's autoindex? If those folders are there in what is returned from Apache, then `folder.api` (which is what `player.html` uses) will return them as a valid folder.
